name: Deploy Preview

on:
  pull_request:
    branches:
      - main  # or the branch you want to target

jobs:
  build_and_preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the node version

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npm run generate

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: 'your-firebase-project-id'
          target: 'your-target-name'  # Optional, specify if you have multiple targets
